version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Docker/backend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /api
    ports:
      - "3000:3000"

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Docker/frontend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "3333:3333"
